### ISSUE TITLE
Unable to install without write permission to the root of the system

### ISSUE THREAD

**Issue by pavelatl** [Dids/clover-builder#101]
Error when i run clover:
Unable to install without write permission to the root of the system.

<img width="663" alt="Снимок экрана 2020-03-23 в 18 22 55" src="https://user-images.githubusercontent.com/26333530/77332806-96dc4880-6d33-11ea-9e25-d1928eff783d.png">

tried this in terminal, but no luck
sudo spctl --master-disable

**Comment by dawidmalina** [comment]
I had the same issue and this can be fixed by disabling partition integrity. Check this link https://www.reddit.com/r/hackintosh/comments/d9pbhy/clover_cannot_install_wo_ensuring_file_system_is/f2crcxt/

**Comment by Dids** [comment]
This is unfortunately an issue with Clover, specifically on Catalina (and newer, I suppose). This can be worked around by disabling SIP (`csrutil` or set `CsrActiveConfig` in your Clover `config.plist`).
