### ISSUE TITLE
Hello, ask a question in hear.

### ISSUE THREAD

**Issue by ghsssss** [Dids/clover-builder#48]
With regard to the problem of excessive memory dispersion, can you solve the problem by upgrading the memoryfix later?@vit9696

**Comment by Dids** [comment]
Not sure what you mean? The included AptioMemoryFix is updated with each new build.

**Comment by ghsssss** [comment]
Sorry, I asked this question to you because there is no issue on vit9696.There is a small percentage of people who have a high probability of booting KP, although the configuration is correct. It is said that the memory is too scattered. I recently tested the boot with memoryfix and lowmemfix.

**Comment by vit9696** [comment]
To solve a problem either buy a new PC or write its firmware from scratch. Unfortunately not much can be done there.

**Comment by solvar0719** [comment]
@vit9696 Hi. I personally don't have this problem but I'm curious in why this happens. It seems that for the same model (XPS 9550 in this case) some machines work absolutely fine while some others don't. Does it have anything to do with the motherboard?

**Comment by anht10** [comment]
lul
