### ISSUE TITLE
need cleanup

### ISSUE THREAD

**Issue by Sher1ocks** [Dids/clover-builder#59]
hi. Dids

left: Official Clover Package, right: Dids's Clover-builder Package
![2018-08-05 8 51 11](https://user-images.githubusercontent.com/2107738/43681374-c6d52de0-988c-11e8-9599-2c711f02e55e.png)

first
in your package, there is no "CloverEFI 64bits BiosBlockIO" on CloverEFI part.

second
![2018-08-05 8 51 25](https://user-images.githubusercontent.com/2107738/43681390-6d6fd77c-988d-11e8-8f7c-fc7574dc39e3.png)
no need apfs.efi and patched apfs.efi
also already include ApfsDriverLoader and AptioInputFix and AptioMemoryFix.

you need to check official clover package

thanks in advance

**Comment by Dids** [comment]
Thanks Sherlocks. I've updated the build script accordingly.

FYI: The build script will soon be replaced by a CLI application more suitable for building Clover.
