### ISSUE TITLE
Override Clover update check logic

### ISSUE THREAD

**Issue by Dids** [Dids/clover-builder#6]
If possible and/or feasible, see if you can override Clover's update check logic (Clover.prefPane?) to look at our GitHub releases instead of the official Clover releases, so we could have much more frequent updates with relative ease.

**Comment by roddy20** [comment]
why? "beta" builds of Clover aren't recommended for all the users
if we need any special build for testing or any special puproses, we can install it manually
and then update to official release when possible

**Comment by Dids** [comment]
Yeah, that's why I haven't implemented it yet, since it seemed silly in the end.
