### ISSUE TITLE
still has issue

### ISSUE THREAD

**Issue by Sher1ocks** [Dids/clover-builder#62]
![2018-08-06 8 11 27](https://user-images.githubusercontent.com/2107738/43713558-f76c9ac8-99b4-11e8-9947-d17556f3b497.png)

left: micky Build_Clover.command_v4.8.9
right: Dids package

thanks for cleanup
but
here is boot sector part. there is problem
also you removed HFS+ driver from previous commit.
was it problem?

**Comment by Sher1ocks** [comment]
HFS+ description already existed in clover package. i think you don't need to add HFS+ description
here is
https://sourceforge.net/p/cloverefiboot/code/HEAD/tree/CloverPackage/package/po/en.po#l641

if there is problem that included HFS+ driver in your package, ignore this comment.

**Comment by Dids** [comment]
Yes, you're right. It was removed due to an oversight.

Any idea if NTFS.efi is required these days, or if it's deprecated and/or unnecessary?

**Comment by Sher1ocks** [comment]
i think NTFS.efi seems to not important.
https://www.insanelymac.com/forum/topic/306320-guide-dual-boot-with-windows-10-and-clover-legacy-or-uefi/?do=findComment&comment=2165880

not sure. but i think this method not support in Clover package.

it's very rare case. nowdays the most of people uses ESP(EFI) or MBR(HFS+,APFS(?))

**Comment by Sher1ocks** [comment]
all is fine. thank you
