### ISSUE TITLE
hello Dids

### ISSUE THREAD

**Issue by Sher1ocks** [Dids/clover-builder#66]
here is report for package about default driver part.

left:micky script, right: your package.
![2018-10-02 7 20 42](https://user-images.githubusercontent.com/2107738/46319154-f7456a80-c613-11e8-94fa-fcd54834ff0a.png)

left:micky script, right: your package.
![2018-10-02 7 20 52](https://user-images.githubusercontent.com/2107738/46319164-01ffff80-c614-11e8-9b9c-6068a1897140.png)
In driver part, you can see default driver(essential files) in micky package.
but recent, clover package was changed for FV2 drivers.
in your package, default driver is missing.

also i tested it with clean status(remove /Library/Preferences/com.projectosx.clover.installer.plist)
still same. need fix

thanks in advance

**Comment by Dids** [comment]
Hi Sherlocks,

So the reason for the changes between the packages is quite simple and done so on purpose, more on this below.


We've been observing that the only drivers new installations actually _need_ are ApfsDriverLoader, AptioMemoryFix and HFSPlus.  
HFSPlus tends to perform better compared to VBoxHfs, ApfsDriverLoader loads apfs.efi so we don't need to keep an extra copy around and finally AptioMemoryFix fixes NVRAM on most boards.

Is there any particular reason you wanted the "official" drivers to be selected by default?

**Comment by Sher1ocks** [comment]
aha did you changed default driver option?
i didn't notice it. i didn't see any commit in your github.
because your package followed default driver in package for long time

**Comment by Dids** [comment]
Ah, no worries. I somewhat recently wrote `clobber` from scratch, which is what this project uses to build Clover now. It's also available on Homebrew, so anyone can very easily build Clover.

The default driver change was very recent, and I've written very shortly about it here: https://github.com/Dids/clobber/releases/tag/v0.0.7

**Comment by Sher1ocks** [comment]
okay. but you are missing important drivers(FSinject/DataHubDxe/SMCHelper)

**Comment by Dids** [comment]
Well, the drivers are still there, just not selected by default.

From what we've been able to gather, FSInject isn't necessary unless you're on a very old version of OS X. DataHub is also only necessary on very old (and rare) UEFI systems/motherboards. Same thing with SMCHelper, where it's very rarely necessary.

All in all, any reasonably modern system should work fine _without_ any of those drivers, and if they're a special/rare case, they can just tick and install them if necessary.

Just for reference, DownloadFritz has also confirmed all of the above, as have a handful of other developers.

**Comment by Sher1ocks** [comment]
i always set configuration for any macos. i'm not exclude any macos.
it's a your build. it's just suggestion. i understand you. and thank you

**Comment by yurikoles** [comment]
@BarbaraPalvin is this resolved now?

**Comment by Dids** [comment]
Well, this is technically a "non-issue" and more of a preference. So far the new defaults provided by these builds have been very well received, so I don't see any reason to revert to the "official" default packages.

**Comment by yurikoles** [comment]
@Dids I can confirm that default driver selection works fine for me, but I was choosing the official selection drivers for long time, then I had decided to try your defaults and it works.

**Comment by ghost** [comment]
Initially I will manually select the 3 drivers, after I found this explanation.
I started using default driver selection and works fine for me too.
