### ISSUE TITLE
Two UEFI Drivers groups in 4692

### ISSUE THREAD

**Issue by yurikoles** [Dids/clover-builder#67]
Those two groups contain different sets of drivers. Seems to be FireVault vs. others.

**Comment by yurikoles** [comment]
![12 53 06](https://user-images.githubusercontent.com/922873/46345895-ecf49200-c64e-11e8-934c-6ddb0b4b7cc4.png)

**Comment by Dids** [comment]
This was apparently a Clover bug, where they forgot to add the translations to the new FV2 group name. It was fixed in the next release.

Reference: https://sourceforge.net/p/cloverefiboot/code/4693

**Comment by yurikoles** [comment]
@Dids, thanks, I saw that it was fixed, but I had forgot to close this ticket.
