### ISSUE TITLE
idea and request

### ISSUE THREAD

**Issue by rtvkris** [Dids/clover-builder#68]
I am asking you if you can do a patch that will help you run the Mojave on the Dual2Core processor, there are many users who have this processor in their hackintosh and every time after the update we have to manually change the file **S/L/UserEventPlugins/com.apple.telemetry.plugin** from HighSierra, could it be automated in clover permanently? I'm sorry but I think you will understand what I wrote because I use hihi translator.

**Comment by yurikoles** [comment]
@rtvkris please file an issue [upstream](https://sourceforge.net/p/cloverefiboot/tickets/)
