### ISSUE TITLE
Text is gibberish

### ISSUE THREAD

**Issue by UnaClocker** [Dids/clover-builder#69]
The text on my clover boot screen is all gibberish. In discussions about the problem on Reddit, we found that 4728 didn't have the gibberish problem, and 4729-4731 did. I just downloaded 4733 to give that a try, but I'm not seeing it mentioned in the changes, so I'm going to assume it's still there.
![gibberish](https://user-images.githubusercontent.com/1596946/47965204-f92a9100-dff8-11e8-8621-8b5fa667792c.jpg)

**Comment by Dids** [comment]
This is a known issue with Clover itself, and not related to this project. The latest version (4735) might have fixed this.
