### ISSUE TITLE
BlockSize:512LegacyApfsContainerScan

### ISSUE THREAD

**Issue by wenco** [Dids/clover-builder#73]
boot fisrt tip this msg:
BlockSize:512LegacyApfsContainerScan:Block device not supportedSuccess
LegacyApfsContainerScan: Entrypoint

![367ebd49f797fc10284e49c312dba3c1](https://user-images.githubusercontent.com/2509597/51455559-22032c80-1d85-11e9-8e12-39c8bc29af6e.jpg)

how can i disable this msg on boot?can u help me? 
and bois setting csm is on

**Comment by Dids** [comment]
As this is unrelated to these automated Clover builds, which is what this repository is for, I'm closing this. For hardware-specific help with Clover itself, seek out help on forums, Reddit and Google.

**Comment by Dids** [comment]
Reopening, as this seems to be a much more common issue than I initially thought.

**Comment by Dids** [comment]
I've received information that while no logic has changed in ApfsDriverLoader, it now includes this message, which can (and most likely will) slow down boot.

It'll likely be fixed and/or removed at some point in the future.

**Comment by wenco** [comment]
yes, slow down boot, about 30seconds.

**Comment by Dids** [comment]
This should be fixed in the next version (any future releases after r4901). Please reopen if the issue still persists.

**Comment by wenco** [comment]
thank you very much!  i install it first time, reboot computer waiting
about 5s loading clover. sure that bug is fixed!

Pauli Jokela <notifications@github.com> 于2019年3月24日周日 下午5:48写道：
