### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by simonpeters** [Dids/clover-builder#77]
Hello!

I tried to install but I got the following errors.

<img width="625" alt="Screenshot 2019-05-28 at 16 25 16" src="https://user-images.githubusercontent.com/714733/58486234-bdf2d980-8165-11e9-8570-42c1d092606e.png">
<img width="620" alt="Screenshot 2019-05-28 at 16 25 25" src="https://user-images.githubusercontent.com/714733/58486235-be8b7000-8165-11e9-828c-7c314e9af0f7.png">

Running 10.14 (18A391)

**Comment by simonpeters** [comment]
using version: v2.4k_r4935

**Comment by Tyborg3** [comment]
Is your EFI Partition located in a different disk?

**Comment by ricktm** [comment]
same issue here, my efi is on a separate partition of the same disk

**Comment by DilsonAbraham** [comment]
I too have the same issue on **macOS Catalina Version 10.15 Beta (19A487m)**
This is when attempting to install the clover boot loader onto the installed disk after a clean install.

It appears that the EFI is on a different partition on the same disk.

This is the Clover installer Log

_> Jun 27 22:11:01 editings-iMac Installer[1568]: @(#)PROGRAM:Install  PROJECT:Install-1000
> Jun 27 22:11:01 editings-iMac Installer[1568]: @(#)PROGRAM:Installer  PROJECT:Installer-953.1
> Jun 27 22:11:01 editings-iMac Installer[1568]: Hardware: iMac18,3 @ 4.20 GHz (x 8), 65536 MB RAM
> Jun 27 22:11:01 editings-iMac Installer[1568]: Running OS Build: Mac OS X 10.15 (19A487m)
> Jun 27 22:11:01 editings-iMac Installer[1568]: Clover v2.4k r4977 EFI bootloader  Installation Log
> Jun 27 22:11:01 editings-iMac Installer[1568]: Opened from: /Users/editing/Downloads/Clover_v2.4k_r4977.pkg
> Jun 27 22:11:01 editings-iMac Installer[1568]: Package Authoring Error: <background> has an unsupported MIME type: image/data
> Jun 27 22:11:01 editings-iMac Installer[1568]: Package Authoring Error: <background-darkAqua> has an unsupported MIME type: image/data
> Jun 27 22:11:01 editings-iMac Installer[1568]: Package Authoring Error: <background_scaling> has an unsupported MIME type: X-NSObject/NSNumber
> Jun 27 22:11:01 editings-iMac Installer[1568]: Package Authoring Error: <background_alignment> has an unsupported MIME type: X-NSObject/NSNumber
> Jun 27 22:11:01 editings-iMac Installer[1568]: Package Authoring Error: <layout-direction> has an unsupported MIME type: X-NSObject/NSNumber
> Jun 27 22:11:12 editings-iMac Installer[1568]: ================================================================================
> Jun 27 22:11:12 editings-iMac Installer[1568]: User picked Custom Install
> Jun 27 22:11:12 editings-iMac Installer[1568]: Choices selected for installation:
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "Clover v2.4k r4977 EFI bootloader"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "Clover for UEFI booting only"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "Install Clover in the ESP"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "Boot Sectors"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "Don't update MBR and PBR sectors"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "UEFI Drivers"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "AptioMemoryFix-64"
> Jun 27 22:11:12 editings-iMac Installer[1568]: 	Install: "HFSPlus"
> Jun 27 22:11:12 editings-iMac Installer[1568]: ================================================================================
> Jun 27 22:11:15 editings-iMac Installer[1568]: Package Authoring Error: Package contains system volume install location content. Installation cannot proceed since installing to the system volume is not possible.
> Jun 27 22:11:15 editings-iMac Installer[1568]: Package Authoring Error: Package contains system volume install location content, and installation will fail: Error Domain=IFInstallErrorDomain Code=-6000 "This package is incompatible with this version of macOS." UserInfo={NSLocalizedRecoveryOptions=(
> 	    Quit
> 	), IFReadOnlyPathsKey={(
> 	    "/EFIROOTDIR/EFI/CLOVER/ACPI/origin",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/Other",
> 	    "/EFIROOTDIR/EFI/CLOVER/ACPI/patched",
> 	    "/EFIROOTDIR/EFI/CLOVER/tools/Shell64.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/CLOVERX64.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/ROM",
> 	    "/EFIROOTDIR/EFI/CLOVER/ACPI/WINDOWS",
> 	    "/EFIROOTDIR/EFI/CLOVER/drivers64UEFI/HFSPlus.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/themes/random/theme.plist",
> 	    "/EFIROOTDIR/EFI/CLOVER/tools/Shell32.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/OEM/SystemProductName/UEFI/config-sample.plist",
> 	    "/EFIROOTDIR/EFI/CLOVER/tools/Shell64U.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/themes/logo_main.png",
> 	    "/EFIROOTDIR/EFI/CLOVER/doc/UEFI boot with Clover.rtf",
> 	    "/EFIROOTDIR/EFI/CLOVER/drivers64UEFI/AptioMemoryFix-64.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/misc",
> 	    "/EFIROOTDIR/EFI/CLOVER/themes/pointer-metal.png",
> 	    "/EFIROOTDIR/EFI/BOOT/BOOTX64.efi",
> 	    "/EFIROOTDIR/EFI/CLOVER/OEM/SystemProductName/UEFI/ACPI/origin",
> 	    "/EFIROOTDIR/EFI/CLOVER/OEM/SystemProductName/ROM",
> 	    "/EFIROOTDIR/EFI/CLOVER/doc/boot1f32-install.sh",
> 	    "/EFIROOTDIR/EFI/CLOVER/themes/embedded/screenshot.png",
> 	    "/EFIROOTDIR/EFI/CLOVER/OEM/SystemProductName/UEFI/kexts/Other",
> 	    "/EFIROOTDIR/EFI/CLOVER/themes/embedded/theme.plist",
> 	    "/EFIROOTDIR/EFI/CLOVER/doc/HowToFixDsdt.txt",
> 	    "/EFIROOTDIR/EFI/CLOVER/doc/HowToInstallOSX.txt",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/10.10",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/10.6",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/10.7",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/10.11",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/10.8",
> 	    "/EFIROOTDIR/EFI/CLOVER/config-sample.plist",
> 	    "/EFIROOTDIR/EFI/CLOVER/kexts/10.9",
> 	    "/EFIROOT_


<img width="626" alt="Screen Shot 2019-06-27 at 9 57 50 PM" src="https://user-images.githubusercontent.com/52308355/60318445-e702b780-9927-11e9-90e5-3c1c04cb40a8.png">

**Comment by Dids** [comment]
Those of you having this issue, could you try the latest version of Clover?

If that fails, could you let me know if you have SIP enabled, also potentially disabling it and trying to install again?

**Comment by mmeiwenlong** [comment]
10.15 dp2 install sudo mount -o rw / this command will still install the option, otherwise it is only the exit option

**Comment by ricktm** [comment]
> Those of you having this issue, could you try the latest version of Clover?
> 
> If that fails, could you let me know if you have SIP enabled, also potentially disabling it and trying to install again?

I have SIP disabled and tried using both 0x67 and 0x3E7, yet unfortunately the installer still will not install. As a work around i've just been manually replacing CLOVERX64.efi

**Comment by fundon** [comment]
try `Suspicious Package App`, just workaround

**Comment by vtrandal** [comment]
> 10.15 dp2 install sudo mount -o rw / this command will still install the option, otherwise it is only the exit option

I have trouble parsing your message. 10.15 looks like a version number. What is dp2? This command will still install the option. What option? Otherwise it is only the exit option. What is "it" ???

What are people doing to install Clover EFI Bootloader?

**Comment by vtrandal** [comment]
> > Those of you having this issue, could you try the latest version of Clover?
> > If that fails, could you let me know if you have SIP enabled, also potentially disabling it and trying to install again?
> 
> I have SIP disabled and tried using both 0x67 and 0x3E7, yet unfortunately the installer still will not install. As a work around i've just been manually replacing CLOVERX64.efi

If replacing CLOVERX64.efi is the goal then I am interested to know where is this CLOVERX64.efi and with what should it be replaced and where does one get that. I feel like I'm about to level up or get killed.

**Comment by Dids** [comment]
Closing this issue, as this is unrelated to these builds of Clover, and more of an issue with Clover itself.
