### ISSUE TITLE
After ver 4895 some change on the sound of HDEF

### ISSUE THREAD

**Issue by phucnguyen2411** [Dids/clover-builder#78]
Hi Clover team, 

I'm trying to update the lasted version of Clover but my hackintosh got the problem with audio.

With the version of clover from 4895 and below the audio can working well with full jack and config via me( appleALC and mapper jack).
But after updated to the lasted version of Clover, my hack just received some jack and incorrect name i already config in the AppleALC. 

So I'm finding in the changelog of Clover and saw you are changed from ver 4903 to remove _DSM of HDEF device. So I think it makes an impact on AppleALC. 

So thanks and hopping new release from your side. :)

**Comment by phucnguyen2411** [comment]
I found the solution to close that issue. :). 

thanks all

**Comment by rodgomesc** [comment]
> I found the solution to close that issue. :).
> 
> thanks all

can you tell the solution for help others with same problem
