### ISSUE TITLE
Shift Key not working

### ISSUE THREAD

**Issue by egar3427** [Dids/clover-builder#79]
Shift key not working in clover. While typing in the bootargs and in the shell64 menu.
I can't type : and other shift key symbol. I notice this in r4979. in r4930 shift key is working fine. I find it difficult when trying to fix EFI boot entry in bcfg boot dump. Thanks

**Comment by Dids** [comment]
Unable to replicate and unlikely to be caused by these custom builds. Try official Clover builds to see if they work, and reopen if necessary.
