### ISSUE TITLE
clover has changed build script, this repo need update

### ISSUE THREAD

**Issue by steve3d** [Dids/clover-builder#80]
this repo depends on clover build script, but as far as I know clover changed the build script recently, and now this repo has no update since then.

please update, thank you.

**Comment by Dids** [comment]
I've nearly finished migrating Clobber to work with the recent changes, so a backlog of builds should queue up today or tomorrow, depending on when I've verified that it's working correctly.

**Comment by Dids** [comment]
Clobber has been fixed: https://github.com/Dids/clobber/releases/tag/v0.3.0

New builds should start popping up soon, as the backlog of failed builds is cleared.
