### ISSUE TITLE
Installation problem Catalina 10.15 Developer Preview 6

### ISSUE THREAD

**Issue by Gnappo85** [Dids/clover-builder#82]
![Clover R5050:5051 Catalina DP6](https://user-images.githubusercontent.com/46998101/63550292-a3e15100-c532-11e9-9f0f-fd1651fa4348.png)

**Comment by azenla** [comment]
This happens to me as well. Not sure what I can really do.

**Comment by ricktm** [comment]
I went back and forth with this too, but ultimately settled on the fix someone else suggested, installed clover to a efi partition on another drive. after I did that, macOS stopped reporting the error when installing. eventually ill use it from the efi on my main drive.

**Comment by Dids** [comment]
This'll need to wait for a fix from the Clover developers. Catalina split the EFI partition into two (one read-only, one read-write), which complicates things for Clover, but should be a relatively easy fix for them.

**Comment by TripsUpStairs** [comment]
> I went back and forth with this too, but ultimately settled on the fix someone else suggested, installed clover to a efi partition on another drive. after I did that, macOS stopped reporting the error when installing. eventually ill use it from the efi on my main drive.

could you elaborate? I'm getting the same error and don't quite get what the work-around is.
EDIT: I was experiencing problems with making a new flashdrive, but got around the problem by disabling SIP.

**Comment by enderaltin** [comment]
have a nice day,
I have the 10.15 update today, can I install?
