### ISSUE TITLE
AptioMemoryFix get deleted at end of clover installation

### ISSUE THREAD

**Issue by memegauste** [Dids/clover-builder#83]
Steps to reproduce:
1. Open Finder with `EFI/CLOVER/drivers/UEFI` open
2. Try to install Clover with AptioMemoryFix selected
3. Notice that at the end of installation EFI driver is deleted

I need to manually copy it at the end of installation and I use it because my boot mechanism is not stable if I don't do it.

**Comment by Dids** [comment]
I can't replicate this on macOS Mojave (10.14.6) and with the latest Clover installer (5056).
Even if I only select AptioMemoryFix, it still upgrades the existing one and doesn't remove it, same with multiple drivers selected.
