### ISSUE TITLE
Package incompatible error in macOS Catalina DP6

### ISSUE THREAD

**Issue by Alin63992** [Dids/clover-builder#84]
While trying to install Clover r5056 on Catalina Developer Preview 6, the installer throws an error saying "This package is incompatible with this version of macOS"A screenshot of the said error is attached to this post.
![Screenshot 2019-08-24 at 20 51 32](https://user-images.githubusercontent.com/38192110/63641121-d4032e00-c6b1-11e9-943c-97c7bec78e25.png)

**Comment by Dids** [comment]
This warning will eventually be fixed by the Clover developers.

**Comment by Alin63992** [comment]
So is it safe to install and ignore the error? 

> This warning will eventually be fixed by the Clover developers.

**Comment by Dids** [comment]
Should be safe, yes.

**Comment by eXcalibre** [comment]
I can confirm its ok to ignore and upgraded just fine on my system after installing the retail version of Catalina.

**Comment by Alin63992** [comment]
> I can confirm its ok to ignore and upgraded just fine on my system after installing the retail version of Catalina.

Yeah I installed it as well and it was fine. thank you for your answers!

**Comment by rgaufman** [comment]
I'm still seeing this version with the latests clover r5104 - any ideas?
