### ISSUE TITLE
Clover source code migrate to github

### ISSUE THREAD

**Issue by BenjaminX** [Dids/clover-builder#85]
Clover move to github
https://github.com/CloverHackyColor/CloverBootloader

pls update build ci code repo

**Comment by Dids** [comment]
Yes, I'm aware of this, and clobber's being updated to support this change.
There's been numerous other changes to Clover too, which have made it harder to account for.

**Comment by Dids** [comment]
Fixed in latest version of [clobber](https://github.com/Dids/clobber). Builds will start flowing in again to this repo, as well as to [cloverdb.com](https://cloverdb.com).
