### ISSUE TITLE
"Cannot install without ensuring the file system is read-write"

### ISSUE THREAD

**Issue by namebee** [Dids/clover-builder#87]
What the title says, I put in my password for ensuring it is.
https://i.imgur.com/sLRFj10.png/

**Comment by HeyItsMeNobody** [comment]
Fixed by disabling SIP.

**Comment by namebee** [comment]
Fixed by disabling SIP.

**Comment by rgaufman** [comment]
What's SIP and how do I disable it?

**Comment by Nembie** [comment]
> What's SIP and how do I disable it?

SIP is an acronym, System Integrity Protection.
I had this issue, you can resolve very easily but you must be sure before running.

This is the steps:
1. Shutdown the Mac
2. Hold down CMD(⌘)+R and press Power button, when boot up you can release the buttons
3. Go to Utility->Terminal 
4. Enter 
> csrutil disable
5. Reboot

Retry ;)
