### ISSUE TITLE
Hide/Remove "Clover Booted from EFI" text

### ISSUE THREAD

**Issue by ouija** [Dids/clover-builder#93]
Hey,

Noticed with the latest version that there is now status text being displayed saying "Clover booted from EFI" (in the top left corner of the bootloader screen/menu) -- How does one update the theme or config.plist file to prevent this? (are you able to hide this text)?

Let me know!  Thanks

**Comment by Dids** [comment]
This is unfortunately outside the scope of this repo, which is primarily for hosting custom Clover builds built with [Clobber](https://github.com/Dids/clobber).
