### ISSUE TITLE
I want to load Acpi Table and DSDT patcher to install WIN7 through clover. Avoid WIN7 0x000000A5 ACPI BSOD ERRORS. Is this idea feasible?

### ISSUE THREAD

**Issue by embeddedsecurity** [Dids/clover-builder#95]
lenovo xiaoxin air14 install WIN7 0x000000A5 ACPI BSOD ERRORS! 
  ![Alt text](https://i.postimg.cc/L6WQ2rBn/QQ-20191204214822.jpg)
  It may be that the motherboard Acpi Table, DSDT patcher and WIN7 are incompatible, causing WIN7 0x000000A5 ACPI BSOD ERRORS
  
  Find the Acpi Table and DSDT patcher compatible with WIN7. Clover loads the Acpi Table and DSDT patcher to guide and install WIN7 to avoid WIN7 0x000000A5 ACPI BSOD ERRORS. Is this idea feasible? If clover does not have this feature, can you consider adding this feature?

  This is a screenshot of lenovo xiaoxin air14 Bios:
  ![Alt text](https://i.postimg.cc/8PJ5yDxz/QQ-20191204180422.jpg)  ![Alt text](https://i.postimg.cc/Wz7zJQdx/BOOT.jpg)。

  This is the lenovo xiaoxin air14 hardware：
  ![Alt text](https://i.postimg.cc/HLJ0sLNr/AIR-14-HWIFO64.jpg)![Alt text](https://i.postimg.cc/HLfwJgGB/AIR-14-GPU.png)

Thank you for your reply and good luck!  I am willing to work with you to solve the problem。

**Comment by Dids** [comment]
This project is for building Clove and its installer package and has nothing to do with Clover itself.

**Comment by embeddedsecurity** [comment]
@Dids Master, can you point me after reading the question? Thank you for your answer, I wish you a happy new year, the new year works smoothly, the boss raises!
