### ISSUE TITLE
Incompatable

### ISSUE THREAD

**Issue by Blurayx** [Dids/clover-builder#97]
I've noticed in the last few months when upgrading EFI bootloader, I get an error: This package is incompatible with this version of macOS. My Hackintosh is still running perfectly(macOS 10.15.3)

<a href="https://imgur.com/Fovs0Pu"><img src="https://i.imgur.com/Fovs0Pu.png" title="source: imgur.com" /></a>

**Comment by Dids** [comment]
You should be able to click "Install Anyway" regardless of the message. This is also the wrong repository for this, plus you don't seem to be using the custom builds provided by this repository.
